### ISSUE TITLE
Interoperable with with Node. JS peer? 

### ISSUE THREAD

**Issue by SyRenity** [lipp/lua-jet#38]
Is the Lua version can interop with Node.js peer? How the methods will be executed in this case?

**Comment by lipp** [comment]
Yes. They can work together .

**Comment by SyRenity** [comment]
How the JS Methods execute then in Lua process?

**Comment by lipp** [comment]
there are different processes communicating over (web)sockets, e.g.:
1 peer (lua) + 1 peer (node.js) + 1 daemon(node.js).
as they all "speak" the same protocol, they are interoperable.

The Methods or States provided by a Peer are invoked when a corresponding message is received over socket, telling to do so. While dispatching the message in the event loop (lua-ev for lua implementation), the Method's "call" callback function or the State's "set" callback function gets executed.
